### ISSUE TITLE
Refinery.removeRecipe don't work

### ISSUE THREAD

**Issue by Tsyklop** [BuildCraft/BuildcraftCompat#65] opened 2016-04-05 13:02 UTC
I wrote this: 
`mods.buildcraft.Refinery.removeRecipe(<liquid:fuel>);`

but the recipe, there is still

buildcraft-compat-7.1.4

Please. fix this.

**Comment by asiekierka** [comment] 2017-11-10 18:37
Duplicate of #54

**Closed as completed by asiekierka** 2017-11-10 18:37 UTC
Labels: duplicate
