### ISSUE TITLE
[Bug] Script can't add Refinery recipes

### ISSUE THREAD

**Issue by karakufire** [BuildCraft/BuildcraftCompat#66] opened 2016-04-29 08:44 UTC
Like as #65, I also encountered similar problem.
I using [these mods](http://pastebin.com/P8BUEcQN), and I found [Null pointer exception](http://pastebin.com/6B5q9VBJ) by Buildcraft-compat.

**Comment by asiekierka** [comment] 2017-11-10 18:37
Duplicate of #54

**Closed as completed by asiekierka** 2017-11-10 18:37 UTC
Labels: duplicate
