### ISSUE TITLE
(Suggestion) Add integration for temperature manipulating items in Mekanism and pnuematicraft.

### ISSUE THREAD

**Issue by border999** [BuildCraft/BuildcraftCompat#95] opened 2021-02-04 12:22 UTC

**Comment by AlexIIL** [comment] 2021-02-04 20:01
Closing as duplicate of https://github.com/BuildCraft/BuildCraft/issues/4633. (Since eventually I'd rather deal with a since issue list - BuildCraft/BuildCraft - rather than multiple).

**Closed as completed by AlexIIL** 2021-02-04 20:01 UTC
